name: Test Project
on: push
jobs:
    test:
        runs-on: windows-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4.2.2
            - name: Install NodeJS
              uses: actions/setup-node@v23
              with:
                node-version: '23.11.0'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test


              
